inherit:
  - base.yaml

training:
  task: quadratic_regression
  data: gaussian
  task_kwargs: {}
  batch_size: 64
  learning_rate: 0.0001
  curriculum:
    points:
      start: 11
      end: 41
      inc: 2
      interval: 2000

out_dir: ../models/quadratic_regression

wandb:
  name: "quadratic_regression_standard"
